// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbieeaupbmvjksvlvyrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiaWVlYXVwYm12amtzdmx2eXJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNzk1MzksImV4cCI6MjA2NDk1NTUzOX0.Zb7CaUId-TxKB_BjI071u6un7J0VO0DSp9tMLYwjPdk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);